name: Stream
options:
  bundleIdPrefix: com.stream
  deploymentTarget:
    iOS: "15.0"
settings:
  base:
    MARKETING_VERSION: "3.0"
    CURRENT_PROJECT_VERSION: "1"
targets:
  Stream:
    type: application
    platform: iOS
    sources:
      - Stream
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.stream.remote
        TARGETED_DEVICE_FAMILY: "1"
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Manual
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_ALLOWED: NO
